# Generated by Django 3.2.4 on 2021-07-12 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_rented_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='retal_period',
            new_name='rental_period',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='retal_price_day',
            new_name='rental_price_day',
        ),
    ]
