# Generated by Django 3.2.4 on 2021-07-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_auto_20210712_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rental_price_day',
            new_name='rental_price_per_day',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='rented_total',
            new_name='rental_total_price',
        ),
    ]
