# Generated by Django 3.2.4 on 2021-07-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_auto_20210712_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='photo_author',
            new_name='author_photo',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='photo_book',
            new_name='book_photo',
        ),
    ]
